name: Build Native
on:
  workflow_dispatch:
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      build_date: ${{ steps.get_date.outputs.date }}
    steps:
      - name: Generate build date
        id: get_date
        run: echo "date=$(date +%s)" >> "$GITHUB_OUTPUT"
  build:
    name: Build ${{ matrix.target }}
    needs: prepare
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./native
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux (x86_64)
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            extension: ""
          # Linux (aarch64)
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            extension: ""
          # macOS (x86_64)
          - os: macos-latest
            target: x86_64-apple-darwin
            extension: ""
          # macOS (aarch64)
          - os: macos-latest
            target: aarch64-apple-darwin
            extension: ""
          # Windows (x86_64)
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            extension: ".exe"
          # Windows (aarch64)
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            extension: ".exe"
    env:
      CI_BUILD_DATE: ${{ needs.prepare.outputs.build_date }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'x86_64-unknown-linux-gnu'
        run: sudo apt-get install -y libcurl4-openssl-dev libssl-dev

      - name: Install arm64 dependencies
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo sed -i 's/^Types: deb/Types: deb\nArchitectures: amd64/' /etc/apt/sources.list.d/ubuntu.sources

          sudo cat <<EOF | sudo tee /etc/apt/sources.list.d/ubuntu-ports.sources
          Types: deb
          Architectures: arm64
          URIs: https://ports.ubuntu.com/ubuntu-ports/
          Suites: noble noble-updates noble-backports noble-security
          Components: main restricted universe multiverse
          Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
          EOF

          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y pkg-config libcurl4-openssl-dev:arm64 libssl-dev:arm64 gcc-aarch64-linux-gnu

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - name: Add Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build (Linux x86_64)
        run: cargo build --release --target ${{ matrix.target }}
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'x86_64-unknown-linux-gnu'

      - name: Build (Linux aarch64)
        run: cargo build --release --target ${{ matrix.target }}
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'aarch64-unknown-linux-gnu'
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
          CC_aarch64_unknown_linux_gnu: aarch64-linux-gnu-gcc
          PKG_CONFIG_ALLOW_CROSS: 1
          PKG_CONFIG_LIBDIR: /usr/lib/aarch64-linux-gnu/pkgconfig
          PKG_CONFIG_SYSROOT_DIR: /

      - name: Build (macOS & Windows)
        run: cargo build --release --target ${{ matrix.target }}
        if: matrix.os == 'macos-latest' || matrix.os == 'windows-latest'

      - name: Upload binary artifact
        uses: actions/upload-artifact@v7
        with:
          name: paperclip-${{ matrix.target }}
          path: native/target/${{ matrix.target }}/release/paperclip${{ matrix.extension }}
